"use client";

import { RecoilRoot } from "recoil";
import "./globals.css";
import { Inter } from "next/font/google";
import { ApolloProvider } from "@apollo/client";
import client from "@/src/core/apollo/client";
import Header from "@/src/components/common/layout/Header";
import Footer from "@/src/components/common/layout/Footer";

const inter = Inter({ subsets: ["latin"] });

// 이걸 주석처리하니까 동작하네요... Next.js 13버전 얼른 학습하겠습니다.
// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ApolloProvider client={client}>
        <RecoilRoot>
          <body className={`${inter.className} w-4/5 min-h-screen mx-auto bg-black`}>
            <Header />
              {children}
            <Footer />
          </body>
        </RecoilRoot>
      </ApolloProvider>
    </html>
  );
}
